{
 "title": "HOME",
 "tags": [ "kubernetes_dashboard/home" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "query": "10m" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_status_ready{condition=\"true\"},namespace)"
    }
   },
   {
    "name": "icon_k8s",
    "query": "https://seeklogo.com/images/K/kubernetes-logo-3A67038EAB-seeklogo.com.png"
   },
   {
    "name": "pod_kind",
    "query": {
     "query": "label_values(kube_pod_info{created_by_kind!=\"<none>\"},created_by_kind)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display:flex; height: 100%; width: 100%;\">\n    <img style=\"margin:auto 0px auto auto; height:49px; width:49px; border-radius:4px;\" src=\"${icon_k8s}\" alt=\"overview\"/>\n  <h1 style=\"margin: auto auto auto 8px; font-weight:bold;\">\n    KUBERNETES DASHBOARD\n  </h1>\n</div>"
   }
  },
  {
   "title": "OVERVIEW",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    { "title": "General Info", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(sum by (node)(kube_node_status_capacity_cpu_cores))",
       "legendFormat": "Nodes"
      },
      { "expr": "count(kube_configmap_created)", "legendFormat": "ConfigMaps" },
      {
       "expr": "count(count by (endpoint)(container_cpu_usage_seconds_total{endpoint!=\"\"}))",
       "legendFormat": "Endpoints"
      },
      { "expr": "count(kube_secret_created)", "legendFormat": "Secrets" },
      {
       "expr": "count(sum by (namespace)(kube_pod_status_ready{condition=\"true\"}))",
       "legendFormat": "Namespaces"
      },
      { "expr": "count(kube_service_info)", "legendFormat": "Services" },
      {
       "expr": "count(count by (image)(rate(container_cpu_usage_seconds_total{image!=\"\"}[$__interval])))",
       "legendFormat": "Images"
      },
      {
       "expr": "count(kube_pod_status_ready{condition=\"true\",pod!=\"\"})",
       "legendFormat": "PODs"
      }
     ]
    },
    { "title": "Pod Kind", "type": "text", "gridPos": { "h": 1, "w": 14, "x": 0, "y": 7 } },
    { "title": "Service Kind", "type": "text", "gridPos": { "h": 1, "w": 10, "x": 14, "y": 7 } },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 14, "x": 0, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by(created_by_kind)(kube_pod_info)",
       "legendFormat": "{{created_by_kind}}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 10, "x": 14, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (type)(kube_service_spec_type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BY CLUSTER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    { "title": "CPU Usage", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 4 } },
    { "title": "Memory Usage", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 4 } },
    {
     "title": "History",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{id=\"/\"}[$__interval]))/sum(kube_node_status_capacity_cpu_cores) *100",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Capacity",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "CPUs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity_cpu_cores)"
      }
     ]
    },
    {
     "title": "Last",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "panelId": 28 }
     ]
    },
    {
     "title": "History",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{id=\"/\"})/sum(kube_node_status_capacity_memory_bytes) *100",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Capacity",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity_memory_bytes)"
      }
     ]
    },
    {
     "title": "Last",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "Min",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      { "panelId": 28 }
     ]
    },
    {
     "title": "Avg",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "panelId": 28 }
     ]
    },
    {
     "title": "Max",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      { "panelId": 28 }
     ]
    },
    {
     "title": "Min",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "Avg",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "panelId": 40 }
     ]
    },
    {
     "title": "Max",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      { "panelId": 40 }
     ]
    },
    { "title": "Fs Usage", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 0, "y": 11 } },
    { "title": "Network Usage", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 11 } },
    {
     "title": "History",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{id=\"/\"})/sum(container_fs_limit_bytes{id=\"/\"})*100",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Capacity",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(container_fs_limit_bytes{id=\"/\"})"
      }
     ]
    },
    {
     "title": "Last",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "panelId": 51 }
     ]
    },
    {
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$__interval]))",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$__interval]))",
       "legendFormat": "Transmit"
      }
     ]
    },
    {
     "title": "Min",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      { "panelId": 51 }
     ]
    },
    {
     "title": "Avg",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "panelId": 51 }
     ]
    },
    {
     "title": "Max",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      { "panelId": 51 }
     ]
    },
    { "type": "text", "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 } },
    { "title": "Pods Usage", "type": "text", "gridPos": { "h": 1, "w": 12, "x": 12, "y": 18 } },
    {
     "title": "History",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "count(kube_pod_status_ready{condition=\"true\",pod!=\"\"})/sum(kube_node_status_capacity_pods)*100",
       "legendFormat": "Usage"
      }
     ]
    },
    {
     "title": "Capacity",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "PODs" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(kube_node_status_capacity_pods)"
      }
     ]
    },
    {
     "title": "Last",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "panelId": 43 }
     ]
    },
    {
     "title": "Min",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 18, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "min" ] } },
     "targets": [
      { "panelId": 43 }
     ]
    },
    {
     "title": "Avg",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 20, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "panelId": 43 }
     ]
    },
    {
     "title": "Max",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      { "panelId": 43 }
     ]
    }
   ]
  },
  {
   "title": "BY WORKER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    { "title": "Last Usage", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
    {
     "title": "Ready Worker",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "count(sum by (node)(container_cpu_usage_seconds_total)>0)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (node)(rate(container_cpu_usage_seconds_total{id=\"/\"}[$__interval]))/sum by (node)(kube_node_status_capacity_cpu_cores))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (node)(rate(container_memory_usage_bytes{id=\"/\"}[$__interval]))/sum by (node)(kube_node_status_capacity_memory_bytes))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Fs Usage",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by  (node)(container_fs_usage_bytes{id=\"/\"})/sum by (node)(container_fs_limit_bytes{id=\"/\"}))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Network Receive",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (node)(rate(container_network_receive_bytes_total{id=\"/\"}[$__interval])))",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Network Transmit",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (node)(rate(container_network_transmit_bytes_total{id=\"/\"}[$__interval])))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    { "title": "Total Usage", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
    {
     "title": "CPU Usage",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (node)(container_cpu_usage_seconds_total{id=\"/\"}))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (node)(container_memory_usage_bytes{id=\"/\"}))",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BY POD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    { "title": "Request / Limit", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
    {
     "title": "CPU Usage",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort(kube_pod_container_resource_requests_cpu_cores{namespace=\"${namespace}\"}/kube_pod_container_resource_limits_cpu_cores{namespace=\"${namespace}\"})",
       "legendFormat": "{{namespace}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort(kube_pod_container_resource_requests_memory_bytes{namespace=\"${namespace}\"}/kube_pod_container_resource_limits_memory_bytes{namespace=\"${namespace}\"})",
       "legendFormat": "{{namespace}} / {{pod}}"
      }
     ]
    },
    { "title": "Last Usage", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
    {
     "title": "Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sort(kube_pod_status_ready{condition=\"true\",namespace=\"${namespace}\"})",
       "legendFormat": "{{namespace}} / {{pod}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort_desc(rate(container_cpu_usage_seconds_total{pod!=\"\",namespace=\"${namespace}\"}[$__interval]))",
       "legendFormat": "{{namespace}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort_desc(rate(container_memory_usage_bytes{container=\"\",pod!=\"\",namespace=\"${namespace}\"}[$__interval]))",
       "legendFormat": "{{namespace}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Fs Usage",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort_desc(container_fs_usage_bytes{pod!=\"\",namespace=\"${namespace}\"})",
       "legendFormat": "{{namespace}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Network Receive",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort_desc(rate(container_network_receive_bytes_total{pod!=\"\",namespace=\"${namespace}\"}[$__interval]))",
       "legendFormat": "{{namespace}} / {{pod}}"
      }
     ]
    },
    {
     "title": "Network Transmit",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sort_desc(rate(container_network_transmit_bytes_total{pod!=\"\",namespace=\"${namespace}\"}[$__interval]))",
       "legendFormat": "{{namespace}} / {{pod}}"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 1, "w": 4, "x": 0, "y": 32 } }
   ]
  },
  {
   "title": "BY POD KIND",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "${pod_kind}",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "repeat": "pod_kind",
     "targets": [
      {
       "expr": "sort(kube_pod_status_phase{namespace=~\"$namespace\",pod!=\"\"}>0) * on (pod) group_left(created_by_kind)(kube_pod_info{namespace=~\"$namespace\",pod!=\"\",created_by_kind=\"${pod_kind}\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "POD Waiting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "POD Status Waiting Reason",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "kube_pod_container_status_waiting_reason>0"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistence Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "kube_persistentvolume_status_phase>0"
      }
     ]
    }
   ]
  }
 ]
}